const data = {
  base1: {
    name: 'Base',
    series: 'Base',
    total: 102,
    releaseDate: '1999/01/09',
    symbol: 'https://images.pokemontcg.io/base1/symbol.png',
  },
  base2: {
    name: 'Jungle',
    series: 'Base',
    total: 64,
    releaseDate: '1999/06/16',
    symbol: 'https://images.pokemontcg.io/base2/symbol.png',
  },
  basep: {
    name: 'Wizards Black Star Promos',
    series: 'Base',
    total: 53,
    releaseDate: '1999/07/01',
    symbol: 'https://images.pokemontcg.io/basep/symbol.png',
  },
  base3: {
    name: 'Fossil',
    series: 'Base',
    total: 62,
    releaseDate: '1999/10/10',
    symbol: 'https://images.pokemontcg.io/base3/symbol.png',
  },
  base4: {
    name: 'Base Set 2',
    series: 'Base',
    total: 130,
    releaseDate: '2000/02/24',
    symbol: 'https://images.pokemontcg.io/base4/symbol.png',
  },
  base5: {
    name: 'Team Rocket',
    series: 'Base',
    total: 83,
    releaseDate: '2000/04/24',
    symbol: 'https://images.pokemontcg.io/base5/symbol.png',
  },
  gym1: {
    name: 'Gym Heroes',
    series: 'Gym',
    total: 132,
    releaseDate: '2000/08/14',
    symbol: 'https://images.pokemontcg.io/gym1/symbol.png',
  },
  gym2: {
    name: 'Gym Challenge',
    series: 'Gym',
    total: 132,
    releaseDate: '2000/10/16',
    symbol: 'https://images.pokemontcg.io/gym2/symbol.png',
  },
  neo1: {
    name: 'Neo Genesis',
    series: 'Neo',
    total: 111,
    releaseDate: '2000/12/16',
    symbol: 'https://images.pokemontcg.io/neo1/symbol.png',
  },
  neo2: {
    name: 'Neo Discovery',
    series: 'Neo',
    total: 75,
    releaseDate: '2001/06/01',
    symbol: 'https://images.pokemontcg.io/neo2/symbol.png',
  },
  si1: {
    name: 'Southern Islands',
    series: 'Other',
    total: 18,
    releaseDate: '2001/07/31',
    symbol: 'https://images.pokemontcg.io/si1/symbol.png',
  },
  neo3: {
    name: 'Neo Revelation',
    series: 'Neo',
    total: 66,
    releaseDate: '2001/09/21',
    symbol: 'https://images.pokemontcg.io/neo3/symbol.png',
  },
  neo4: {
    name: 'Neo Destiny',
    series: 'Neo',
    total: 113,
    releaseDate: '2002/02/28',
    symbol: 'https://images.pokemontcg.io/neo4/symbol.png',
  },
  base6: {
    name: 'Legendary Collection',
    series: 'Other',
    total: 110,
    releaseDate: '2002/05/24',
    symbol: 'https://images.pokemontcg.io/base6/symbol.png',
  },
  ecard1: {
    name: 'Expedition Base Set',
    series: 'E-Card',
    total: 165,
    releaseDate: '2002/09/15',
    symbol: 'https://images.pokemontcg.io/ecard1/symbol.png',
  },
  ecard2: {
    name: 'Aquapolis',
    series: 'E-Card',
    total: 186,
    releaseDate: '2003/01/15',
    symbol: 'https://images.pokemontcg.io/ecard2/symbol.png',
  },
  ecard3: {
    name: 'Skyridge',
    series: 'E-Card',
    total: 182,
    releaseDate: '2003/05/12',
    symbol: 'https://images.pokemontcg.io/ecard3/symbol.png',
  },
  ex1: {
    name: 'Ruby & Sapphire',
    series: 'EX',
    total: 109,
    releaseDate: '2003/07/01',
    symbol: 'https://images.pokemontcg.io/ex1/symbol.png',
  },
  ex2: {
    name: 'Sandstorm',
    series: 'EX',
    total: 100,
    releaseDate: '2003/09/18',
    symbol: 'https://images.pokemontcg.io/ex2/symbol.png',
  },
  ex3: {
    name: 'Dragon',
    series: 'EX',
    total: 97,
    releaseDate: '2003/09/18',
    symbol: 'https://images.pokemontcg.io/ex3/symbol.png',
  },
  np: {
    name: 'Nintendo Black Star Promos',
    series: 'NP',
    total: 40,
    releaseDate: '2003/10/01',
    symbol: 'https://images.pokemontcg.io/np/symbol.png',
  },
  ex4: {
    name: 'Team Magma vs Team Aqua',
    series: 'EX',
    total: 95,
    releaseDate: '2004/03/01',
    symbol: 'https://images.pokemontcg.io/ex4/symbol.png',
  },
  ex5: {
    name: 'Hidden Legends',
    series: 'EX',
    total: 101,
    releaseDate: '2004/06/01',
    symbol: 'https://images.pokemontcg.io/ex5/symbol.png',
  },
  ex6: {
    name: 'FireRed & LeafGreen',
    series: 'EX',
    total: 112,
    releaseDate: '2004/09/01',
    symbol: 'https://images.pokemontcg.io/ex6/symbol.png',
  },
  pop1: {
    name: 'POP Series 1',
    series: 'POP',
    total: 17,
    releaseDate: '2004/09/01',
    symbol: 'https://images.pokemontcg.io/pop1/symbol.png',
  },
  ex7: {
    name: 'Team Rocket Returns',
    series: 'EX',
    total: 109,
    releaseDate: '2004/11/01',
    symbol: 'https://images.pokemontcg.io/ex7/symbol.png',
  },
  ex8: {
    name: 'Deoxys',
    series: 'EX',
    total: 107,
    releaseDate: '2005/02/01',
    symbol: 'https://images.pokemontcg.io/ex8/symbol.png',
  },
  ex9: {
    name: 'Emerald',
    series: 'EX',
    total: 106,
    releaseDate: '2005/05/01',
    symbol: 'https://images.pokemontcg.io/ex9/symbol.png',
  },
  ex10: {
    name: 'Unseen Forces',
    series: 'EX',
    total: 117,
    releaseDate: '2005/08/01',
    symbol: 'https://images.pokemontcg.io/ex10/symbol.png',
  },
  pop2: {
    name: 'POP Series 2',
    series: 'POP',
    total: 17,
    releaseDate: '2005/08/01',
    symbol: 'https://images.pokemontcg.io/pop2/symbol.png',
  },
  ex11: {
    name: 'Delta Species',
    series: 'EX',
    total: 114,
    releaseDate: '2005/10/31',
    symbol: 'https://images.pokemontcg.io/ex11/symbol.png',
  },
  ex12: {
    name: 'Legend Maker',
    series: 'EX',
    total: 93,
    releaseDate: '2006/02/01',
    symbol: 'https://images.pokemontcg.io/ex12/symbol.png',
  },
  pop3: {
    name: 'POP Series 3',
    series: 'POP',
    total: 17,
    releaseDate: '2006/04/01',
    symbol: 'https://images.pokemontcg.io/pop3/symbol.png',
  },
  ex13: {
    name: 'Holon Phantoms',
    series: 'EX',
    total: 111,
    releaseDate: '2006/05/01',
    symbol: 'https://images.pokemontcg.io/ex13/symbol.png',
  },
  ex14: {
    name: 'Crystal Guardians',
    series: 'EX',
    total: 100,
    releaseDate: '2006/08/01',
    symbol: 'https://images.pokemontcg.io/ex14/symbol.png',
  },
  pop4: {
    name: 'POP Series 4',
    series: 'POP',
    total: 17,
    releaseDate: '2006/08/01',
    symbol: 'https://images.pokemontcg.io/pop4/symbol.png',
  },
  ex15: {
    name: 'Dragon Frontiers',
    series: 'EX',
    total: 101,
    releaseDate: '2006/11/01',
    symbol: 'https://images.pokemontcg.io/ex15/symbol.png',
  },
  pop5: {
    name: 'POP Series 5',
    series: 'POP',
    total: 17,
    releaseDate: '2007/03/01',
    symbol: 'https://images.pokemontcg.io/pop5/symbol.png',
  },
  ex16: {
    name: 'Power Keepers',
    series: 'EX',
    total: 108,
    releaseDate: '2007/02/02',
    symbol: 'https://images.pokemontcg.io/ex16/symbol.png',
  },
  dp1: {
    name: 'Diamond & Pearl',
    series: 'Diamond & Pearl',
    total: 130,
    releaseDate: '2007/05/01',
    symbol: 'https://images.pokemontcg.io/dp1/symbol.png',
  },
  dpp: {
    name: 'DP Black Star Promos',
    series: 'Diamond & Pearl',
    total: 56,
    releaseDate: '2007/05/01',
    symbol: 'https://images.pokemontcg.io/dpp/symbol.png',
  },
  dp2: {
    name: 'Mysterious Treasures',
    series: 'Diamond & Pearl',
    total: 124,
    releaseDate: '2007/08/01',
    symbol: 'https://images.pokemontcg.io/dp2/symbol.png',
  },
  pop6: {
    name: 'POP Series 6',
    series: 'POP',
    total: 17,
    releaseDate: '2007/09/01',
    symbol: 'https://images.pokemontcg.io/pop6/symbol.png',
  },
  dp3: {
    name: 'Secret Wonders',
    series: 'Diamond & Pearl',
    total: 132,
    releaseDate: '2007/11/01',
    symbol: 'https://images.pokemontcg.io/dp3/symbol.png',
  },
  dp4: {
    name: 'Great Encounters',
    series: 'Diamond & Pearl',
    total: 106,
    releaseDate: '2008/02/01',
    symbol: 'https://images.pokemontcg.io/dp4/symbol.png',
  },
  pop7: {
    name: 'POP Series 7',
    series: 'POP',
    total: 17,
    releaseDate: '2008/03/01',
    symbol: 'https://images.pokemontcg.io/pop7/symbol.png',
  },
  dp5: {
    name: 'Majestic Dawn',
    series: 'Diamond & Pearl',
    total: 100,
    releaseDate: '2008/05/01',
    symbol: 'https://images.pokemontcg.io/dp5/symbol.png',
  },
  dp6: {
    name: 'Legends Awakened',
    series: 'Diamond & Pearl',
    total: 146,
    releaseDate: '2008/08/01',
    symbol: 'https://images.pokemontcg.io/dp6/symbol.png',
  },
  pop8: {
    name: 'POP Series 8',
    series: 'POP',
    total: 17,
    releaseDate: '2008/09/01',
    symbol: 'https://images.pokemontcg.io/pop8/symbol.png',
  },
  dp7: {
    name: 'Stormfront',
    series: 'Diamond & Pearl',
    total: 103,
    releaseDate: '2008/11/01',
    symbol: 'https://images.pokemontcg.io/dp7/symbol.png',
  },
  pl1: {
    name: 'Platinum',
    series: 'Platinum',
    total: 130,
    releaseDate: '2009/02/11',
    symbol: 'https://images.pokemontcg.io/pl1/symbol.png',
  },
  pop9: {
    name: 'POP Series 9',
    series: 'POP',
    total: 17,
    releaseDate: '2009/03/01',
    symbol: 'https://images.pokemontcg.io/pop9/symbol.png',
  },
  pl2: {
    name: 'Rising Rivals',
    series: 'Platinum',
    total: 114,
    releaseDate: '2009/05/16',
    symbol: 'https://images.pokemontcg.io/pl2/symbol.png',
  },
  pl3: {
    name: 'Supreme Victors',
    series: 'Platinum',
    total: 150,
    releaseDate: '2009/08/19',
    symbol: 'https://images.pokemontcg.io/pl3/symbol.png',
  },
  pl4: {
    name: 'Arceus',
    series: 'Platinum',
    total: 99,
    releaseDate: '2009/11/04',
    symbol: 'https://images.pokemontcg.io/pl4/symbol.png',
  },
  ru1: {
    name: 'Pokémon Rumble',
    series: 'Other',
    total: 16,
    releaseDate: '2009/12/02',
    symbol: 'https://images.pokemontcg.io/ru1/symbol.png',
  },
  hgss1: {
    name: 'HeartGold & SoulSilver',
    series: 'HeartGold & SoulSilver',
    total: 123,
    releaseDate: '2010/02/10',
    symbol: 'https://images.pokemontcg.io/hgss1/symbol.png',
  },
  hsp: {
    name: 'HGSS Black Star Promos',
    series: 'HeartGold & SoulSilver',
    total: 25,
    releaseDate: '2010/02/10',
    symbol: 'https://images.pokemontcg.io/hsp/symbol.png',
  },
  hgss2: {
    name: 'HS—Unleashed',
    series: 'HeartGold & SoulSilver',
    total: 95,
    releaseDate: '2010/05/12',
    symbol: 'https://images.pokemontcg.io/hgss2/symbol.png',
  },
  hgss3: {
    name: 'HS—Undaunted',
    series: 'HeartGold & SoulSilver',
    total: 90,
    releaseDate: '2010/08/18',
    symbol: 'https://images.pokemontcg.io/hgss3/symbol.png',
  },
  hgss4: {
    name: 'HS—Triumphant',
    series: 'HeartGold & SoulSilver',
    total: 102,
    releaseDate: '2010/11/03',
    symbol: 'https://images.pokemontcg.io/hgss4/symbol.png',
  },
  col1: {
    name: 'Call of Legends',
    series: 'HeartGold & SoulSilver',
    total: 106,
    releaseDate: '2011/02/09',
    symbol: 'https://images.pokemontcg.io/col1/symbol.png',
  },
  bwp: {
    name: 'BW Black Star Promos',
    series: 'Black & White',
    total: 101,
    releaseDate: '2011/03/01',
    symbol: 'https://images.pokemontcg.io/bwp/symbol.png',
  },
  bw1: {
    name: 'Black & White',
    series: 'Black & White',
    total: 114,
    releaseDate: '2011/04/25',
    symbol: 'https://images.pokemontcg.io/bw1/symbol.png',
  },
  mcd11: {
    name: "McDonald's Collection 2011",
    series: 'Other',
    total: 12,
    releaseDate: '2011/06/17',
    symbol: 'https://images.pokemontcg.io/mcd11/symbol.png',
  },
  bw2: {
    name: 'Emerging Powers',
    series: 'Black & White',
    total: 98,
    releaseDate: '2011/08/31',
    symbol: 'https://images.pokemontcg.io/bw2/symbol.png',
  },
  bw3: {
    name: 'Noble Victories',
    series: 'Black & White',
    total: 102,
    releaseDate: '2011/11/16',
    symbol: 'https://images.pokemontcg.io/bw3/symbol.png',
  },
  bw4: {
    name: 'Next Destinies',
    series: 'Black & White',
    total: 103,
    releaseDate: '2012/02/08',
    symbol: 'https://images.pokemontcg.io/bw4/symbol.png',
  },
  bw5: {
    name: 'Dark Explorers',
    series: 'Black & White',
    total: 111,
    releaseDate: '2012/05/09',
    symbol: 'https://images.pokemontcg.io/bw5/symbol.png',
  },
  mcd12: {
    name: "McDonald's Collection 2012",
    series: 'Other',
    total: 12,
    releaseDate: '2012/06/15',
    symbol: 'https://images.pokemontcg.io/mcd12/symbol.png',
  },
  bw6: {
    name: 'Dragons Exalted',
    series: 'Black & White',
    total: 128,
    releaseDate: '2012/08/15',
    symbol: 'https://images.pokemontcg.io/bw6/symbol.png',
  },
  dv1: {
    name: 'Dragon Vault',
    series: 'Black & White',
    total: 20,
    releaseDate: '2012/10/05',
    symbol: 'https://images.pokemontcg.io/dv1/symbol.png',
  },
  bw7: {
    name: 'Boundaries Crossed',
    series: 'Black & White',
    total: 153,
    releaseDate: '2012/11/07',
    symbol: 'https://images.pokemontcg.io/bw7/symbol.png',
  },
  bw8: {
    name: 'Plasma Storm',
    series: 'Black & White',
    total: 138,
    releaseDate: '2013/02/06',
    symbol: 'https://images.pokemontcg.io/bw8/symbol.png',
  },
  bw9: {
    name: 'Plasma Freeze',
    series: 'Black & White',
    total: 122,
    releaseDate: '2013/05/08',
    symbol: 'https://images.pokemontcg.io/bw9/symbol.png',
  },
  bw10: {
    name: 'Plasma Blast',
    series: 'Black & White',
    total: 105,
    releaseDate: '2013/08/14',
    symbol: 'https://images.pokemontcg.io/bw10/symbol.png',
  },
  xyp: {
    name: 'XY Black Star Promos',
    series: 'XY',
    total: 183,
    releaseDate: '2013/10/12',
    symbol: 'https://images.pokemontcg.io/xyp/symbol.png',
  },
  bw11: {
    name: 'Legendary Treasures',
    series: 'Black & White',
    total: 115,
    releaseDate: '2013/11/06',
    symbol: 'https://images.pokemontcg.io/bw11/symbol.png',
  },
  xy0: {
    name: 'Kalos Starter Set',
    series: 'XY',
    total: 39,
    releaseDate: '2013/11/08',
    symbol: 'https://images.pokemontcg.io/xy0/symbol.png',
  },
  xy1: {
    name: 'XY',
    series: 'XY',
    total: 146,
    releaseDate: '2014/02/05',
    symbol: 'https://images.pokemontcg.io/xy1/symbol.png',
  },
  xy2: {
    name: 'Flashfire',
    series: 'XY',
    total: 109,
    releaseDate: '2014/05/07',
    symbol: 'https://images.pokemontcg.io/xy2/symbol.png',
  },
  xy3: {
    name: 'Furious Fists',
    series: 'XY',
    total: 113,
    releaseDate: '2014/08/13',
    symbol: 'https://images.pokemontcg.io/xy3/symbol.png',
  },
  xy4: {
    name: 'Phantom Forces',
    series: 'XY',
    total: 119,
    releaseDate: '2014/11/05',
    symbol: 'https://images.pokemontcg.io/xy4/symbol.png',
  },
  xy5: {
    name: 'Primal Clash',
    series: 'XY',
    total: 160,
    releaseDate: '2015/02/04',
    symbol: 'https://images.pokemontcg.io/xy5/symbol.png',
  },
  dc1: {
    name: 'Double Crisis',
    series: 'XY',
    total: 34,
    releaseDate: '2015/03/25',
    symbol: 'https://images.pokemontcg.io/dc1/symbol.png',
  },
  xy6: {
    name: 'Roaring Skies',
    series: 'XY',
    total: 110,
    releaseDate: '2015/05/06',
    symbol: 'https://images.pokemontcg.io/xy6/symbol.png',
  },
  xy7: {
    name: 'Ancient Origins',
    series: 'XY',
    total: 100,
    releaseDate: '2015/08/12',
    symbol: 'https://images.pokemontcg.io/xy7/symbol.png',
  },
  xy8: {
    name: 'BREAKthrough',
    series: 'XY',
    total: 164,
    releaseDate: '2015/11/04',
    symbol: 'https://images.pokemontcg.io/xy8/symbol.png',
  },
  xy9: {
    name: 'BREAKpoint',
    series: 'XY',
    total: 123,
    releaseDate: '2016/02/03',
    symbol: 'https://images.pokemontcg.io/xy9/symbol.png',
  },
  g1: {
    name: 'Generations',
    series: 'XY',
    total: 115,
    releaseDate: '2016/02/22',
    symbol: 'https://images.pokemontcg.io/g1/symbol.png',
  },
  xy10: {
    name: 'Fates Collide',
    series: 'XY',
    total: 125,
    releaseDate: '2016/05/02',
    symbol: 'https://images.pokemontcg.io/xy10/symbol.png',
  },
  xy11: {
    name: 'Steam Siege',
    series: 'XY',
    total: 116,
    releaseDate: '2016/08/03',
    symbol: 'https://images.pokemontcg.io/xy11/symbol.png',
  },
  mcd16: {
    name: "McDonald's Collection 2016",
    series: 'Other',
    total: 12,
    releaseDate: '2016/08/19',
    symbol: 'https://images.pokemontcg.io/mcd16/symbol.png',
  },
  xy12: {
    name: 'Evolutions',
    series: 'XY',
    total: 109,
    releaseDate: '2016/11/02',
    symbol: 'https://images.pokemontcg.io/xy12/symbol.png',
  },
  sm1: {
    name: 'Sun & Moon',
    series: 'Sun & Moon',
    total: 149,
    releaseDate: '2017/02/03',
    symbol: 'https://images.pokemontcg.io/sm1/symbol.png',
  },
  smp: {
    name: 'SM Black Star Promos',
    series: 'Sun & Moon',
    total: 156,
    releaseDate: '2017/02/03',
    symbol: 'https://images.pokemontcg.io/smp/symbol.png',
  },
  sm2: {
    name: 'Guardians Rising',
    series: 'Sun & Moon',
    total: 145,
    releaseDate: '2017/05/05',
    symbol: 'https://images.pokemontcg.io/sm2/symbol.png',
  },
  sm3: {
    name: 'Burning Shadows',
    series: 'Sun & Moon',
    total: 147,
    releaseDate: '2017/08/05',
    symbol: 'https://images.pokemontcg.io/sm3/symbol.png',
  },
  sm35: {
    name: 'Shining Legends',
    series: 'Sun & Moon',
    total: 78,
    releaseDate: '2017/10/06',
    symbol: 'https://images.pokemontcg.io/sm35/symbol.png',
  },
  sm4: {
    name: 'Crimson Invasion',
    series: 'Sun & Moon',
    total: 111,
    releaseDate: '2017/11/03',
    symbol: 'https://images.pokemontcg.io/sm4/symbol.png',
  },
  sm5: {
    name: 'Ultra Prism',
    series: 'Sun & Moon',
    total: 156,
    releaseDate: '2018/02/02',
    symbol: 'https://images.pokemontcg.io/sm5/symbol.png',
  },
  sm6: {
    name: 'Forbidden Light',
    series: 'Sun & Moon',
    total: 146,
    releaseDate: '2018/05/04',
    symbol: 'https://images.pokemontcg.io/sm6/symbol.png',
  },
  sm7: {
    name: 'Celestial Storm',
    series: 'Sun & Moon',
    total: 168,
    releaseDate: '2018/08/03',
    symbol: 'https://images.pokemontcg.io/sm7/symbol.png',
  },
  sm75: {
    name: 'Dragon Majesty',
    series: 'Sun & Moon',
    total: 78,
    releaseDate: '2018/09/07',
    symbol: 'https://images.pokemontcg.io/sm75/symbol.png',
  },
  sm8: {
    name: 'Lost Thunder',
    series: 'Sun & Moon',
    total: 236,
    releaseDate: '2018/11/02',
    symbol: 'https://images.pokemontcg.io/sm8/symbol.png',
  },
  sm9: {
    name: 'Team Up',
    series: 'Sun & Moon',
    total: 196,
    releaseDate: '2019/02/01',
    symbol: 'https://images.pokemontcg.io/sm9/symbol.png',
  },
  det1: {
    name: 'Detective Pikachu',
    series: 'Sun & Moon',
    total: 18,
    releaseDate: '2019/04/05',
    symbol: 'https://images.pokemontcg.io/det1/symbol.png',
  },
  sm10: {
    name: 'Unbroken Bonds',
    series: 'Sun & Moon',
    total: 234,
    releaseDate: '2019/05/03',
    symbol: 'https://images.pokemontcg.io/sm10/symbol.png',
  },
  sm11: {
    name: 'Unified Minds',
    series: 'Sun & Moon',
    total: 258,
    releaseDate: '2019/08/02',
    symbol: 'https://images.pokemontcg.io/sm11/symbol.png',
  },
  sm115: {
    name: 'Hidden Fates',
    series: 'Sun & Moon',
    total: 69,
    releaseDate: '2019/08/23',
    symbol: 'https://images.pokemontcg.io/sm115/symbol.png',
  },
  sma: {
    name: 'Shiny Vault',
    series: 'Sun & Moon',
    total: 94,
    releaseDate: '2019/08/23',
    symbol: 'https://images.pokemontcg.io/sma/symbol.png',
  },
  mcd19: {
    name: "McDonald's Collection 2019",
    series: 'Other',
    total: 12,
    releaseDate: '2019/10/15',
    symbol: 'https://images.pokemontcg.io/mcd19/symbol.png',
  },
  sm12: {
    name: 'Cosmic Eclipse',
    series: 'Sun & Moon',
    total: 271,
    releaseDate: '2019/11/01',
    symbol: 'https://images.pokemontcg.io/sm12/symbol.png',
  },
  swshp: {
    name: 'SWSH Black Star Promos',
    series: 'Sword & Shield',
    total: 103,
    releaseDate: '2019/11/15',
    symbol: 'https://images.pokemontcg.io/swshp/symbol.png',
  },
  swsh1: {
    name: 'Sword & Shield',
    series: 'Sword & Shield',
    total: 216,
    releaseDate: '2020/02/07',
    symbol: 'https://images.pokemontcg.io/swsh1/symbol.png',
  },
  swsh2: {
    name: 'Rebel Clash',
    series: 'Sword & Shield',
    total: 209,
    releaseDate: '2020/05/01',
    symbol: 'https://images.pokemontcg.io/swsh2/symbol.png',
  },
  swsh3: {
    name: 'Darkness Ablaze',
    series: 'Sword & Shield',
    total: 201,
    releaseDate: '2020/08/14',
    symbol: 'https://images.pokemontcg.io/swsh3/symbol.png',
  },
  swsh35: {
    name: "Champion's Path",
    series: 'Sword & Shield',
    total: 80,
    releaseDate: '2020/09/25',
    symbol: 'https://images.pokemontcg.io/swsh35/symbol.png',
  },
  swsh4: {
    name: 'Vivid Voltage',
    series: 'Sword & Shield',
    total: 203,
    releaseDate: '2020/11/13',
    symbol: 'https://images.pokemontcg.io/swsh4/symbol.png',
  },
  swsh45: {
    name: 'Shining Fates',
    series: 'Sword & Shield',
    total: 73,
    releaseDate: '2021/02/19',
    symbol: 'https://images.pokemontcg.io/swsh45/symbol.png',
  },
  swsh45sv: {
    name: 'Shiny Vault',
    series: 'Sword & Shield',
    total: 122,
    releaseDate: '2021/02/19',
    symbol: 'https://images.pokemontcg.io/swsh45sv/symbol.png',
  },
  swsh5: {
    name: 'Battle Styles',
    series: 'Sword & Shield',
    total: 183,
    releaseDate: '2021/03/19',
    symbol: 'https://images.pokemontcg.io/swsh5/symbol.png',
  },
};

export default data;
